import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadataBase = new URL("https://codeloom.studio");

export const metadata = {
  title: "Codeloom — Design & Development Studio",
  description:
    "Codeloom Studio — Product design, development and growth for startups and founders. We craft delightful web and mobile experiences that convert.",
  applicationName: "Codeloom Studio",
  authors: [{ name: "Codeloom Studio", url: "https://codeloom.studio" }],
  keywords: [
    "design",
    "development",
    "product design",
    "startup",
    "web development",
    "mobile app",
  ],
  openGraph: {
    title: "Codeloom — Design & Development Studio",
    description:
      "Product design, development and growth for startups and founders. We craft delightful web and mobile experiences that convert.",
    url: "https://codeloom.studio",
    siteName: "Codeloom",
    images: [
      {
        url: "/assets/og-image.png",
        width: 1200,
        height: 630,
        alt: "Codeloom — Design & Development Studio",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Codeloom — Design & Development Studio",
    description:
      "Product design, development and growth for startups and founders.",
    images: ["/assets/og-image.png"],
    site: "@codeloom",
  },
  icons: {
    icon: "/assets/C.svg",
    shortcut: "/assets/C.svg",
    apple: "/assets/C.svg",
    other: [
      { url: "/assets/C.svg", rel: "mask-icon", color: "#F54A00" },
    ],
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

const schemaOrg = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "Codeloom Studio",
  url: "https://codeloom.studio",
  logo: "https://codeloom.studio/assets/codeloom-logo.svg",
  sameAs: [
    "https://www.linkedin.com/company/codeloom-studio/",
    "https://twitter.com/codeloom",
  ],
  contactPoint: [
    {
      "@type": "ContactPoint",
      telephone: "+91-9137421926",
      contactType: "customer support",
      areaServed: "IN",
      availableLanguage: ["English"],
    },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Manifest and theme */}
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#F54A00" />
        {/* Favicons (PNG fallbacks generated by scripts) */}
        <link rel="apple-touch-icon" sizes="180x180" href="/assets/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/assets/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/assets/favicon-16x16.png" />
        <link rel="icon" type="image/png" sizes="48x48" href="/assets/favicon-48x48.png" />
        <link rel="icon" type="image/png" sizes="96x96" href="/assets/favicon-96x96.png" />
        <link rel="icon" type="image/png" sizes="192x192" href="/assets/android-chrome-192x192.png" />
        <link rel="icon" type="image/png" sizes="512x512" href="/assets/android-chrome-512x512.png" />
        {/* Fallback SVG (some browsers support svg favicons) */}
        <link rel="icon" href="/assets/C.svg" />
        <link rel="mask-icon" href="/assets/C.svg" color="#F54A00" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* JSON-LD Organization schema for SEO */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(schemaOrg) }}
        />

        {children}
      </body>
    </html>
  );
}
